name: Run on PR Comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  test_running:
    name: Fail README.md
    if: ${{ startsWith(github.event.comment.body, '@github-actions test') && github.event.issue.pull_request != null }}
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch origin +refs/pull/${{ github.event.issue.number }}/merge
        git checkout FETCH_HEAD
        
    - name: Fail something
      run: echo "::error file=README.md,line=3,col=2::This was added from the PR comment workflow"
