name: Dump ACTIONS_CACHE_URL

on: [pull_request]

jobs:
  dump:
    name: Dump ACTIONS_CACHE_URL
    runs-on: ubuntu-latest

    steps:
      - run: echo "$ACTIONS_CACHE_URL"
        env:
          ACTIONS_CACHE_URL: $ACTIONS_CACHE_URL
          
      - run: echo "$ACTIONS_RUNTIME_URL"
        env:
          ACTIONS_RUNTIME_URL: $ACTIONS_RUNTIME_URL
